config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("books/", include("books.urls",  namespace="books")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import home


app_name = "core"

urlpatterns = [
    path("", home, name="home"),
]

users/urls.py
from django.urls import path
from users.views import LoginView, logout_view, SignupView, MypageView, EditProfileView, ChangePasswordView

app_name = "users"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", logout_view, name="logout"),
    path("signup/", SignupView.as_view(), name="signup"),
    path("<int:pk>/", MypageView.as_view(), name="mypage"),
    path("update-profile/", EditProfileView.as_view(), name="update_profile"),
    path("change-password/", ChangePasswordView.as_view(), name="change_password"),
]

templates/partials/footer.html
<footer class="bottom-0 bg-gray-700 text-white p-3 flex flex-col justify-center items-center">
    <div>&copy; Kariu Studio</div>
    <div>Created by Kariu</div>
</footer>

templates/partials/header.html
{% load static %}
<header id="header" class="container flex justify-between items-center max-w-full px-6 bg-headercolor">
    <a href="{% url 'core:home' %}">
        <img src="{% static 'img/logo.png' %}" />
    </a>

    <div class="mr-2">
        {% if user.is_authenticated %}
            <a class="mr-3 text-gray-500" href="{% url 'users:logout'%}">Log out</a>
            <a class=" text-gray-500 font-bold" href="{% url 'users:mypage' user.pk%}">My page</a>
        {%else%}
            <a class="mr-3 text-gray-500" href="{% url 'users:login'%}">Log in</a>
            <a class=" text-gray-500 font-bold" href="{% url 'users:signup'%}">Sign up</a>
        {% endif %}
    </div>
</header>

templates/partials/paginator.html
<div class="my-14 flex justify-center items-center text-gray-400">
    {% if page_obj.number >= 6 %}
        <a class="mx-2 px-3 py-1 border rounded hover:bg-gray-100" href="?page=1"><<</a>
        <span>···</span>
    {% endif %}

    {% if page_obj.has_previous %}
        <a class="mx-2 px-4 py-1 border rounded hover:bg-gray-100" href="?page={{page_obj.previous_page_number}}"> < </a>
    {% endif %}

    {% for page in page_obj.paginator.page_range %}
        {% if page <= page_obj.number|add:4 and page >= page_obj.number|add:-4 %}
            <a class="px-4 py-1 border rounded  
            {% if page_obj.number == forloop.counter %}
                bg-maincolor text-white
            {% else %}
                hover:bg-gray-100
            {% endif %}" 
            href="?page={{forloop.counter}}">{{forloop.counter}}</a>
            {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <a class="mx-2 px-4 py-1 border rounded hover:bg-gray-100" href="?page={{page_obj.next_page_number}}"> > </a>
    {% endif %}
</div>