books/urls.py
from django.urls import path
from books.views import BooksView, BookDetail, BookCreate, BookDelete, BookUpdate

app_name = "books"

urlpatterns = [
    path("", BooksView.as_view(), name="books"),
    path("<int:pk>/", BookDetail.as_view(), name="book"),
    path("create/", BookCreate.as_view(), name="create"),
    path("update/<int:pk>/", BookUpdate.as_view(), name="update"),
    path("delete/<int:pk>/", BookDelete.as_view(), name="delete"),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("books/", include("books.urls",  namespace="books")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import home


app_name = "core"

urlpatterns = [
    path("", home, name="home"),
]

movies/urls.py
from django.urls import path
from movies.views import MoviesView, MovieDetail, UpdateMovie, CreateMovie, DeleteMovie

app_name = "movies"

urlpatterns = [
    path("", MoviesView.as_view(), name="movies"),
    path("<int:pk>/", MovieDetail.as_view(), name="movie"),
    path("<int:pk>/update/", UpdateMovie.as_view(), name="update"),
    path("create/", CreateMovie.as_view(), name="create"),
    path("<int:pk>/delete/", DeleteMovie.as_view(), name="delete"),
]

users/urls.py
from django.urls import path
from users.views import LoginView, logout_view, SignupView, MypageView, EditProfileView, ChangePasswordView

app_name = "users"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", logout_view, name="logout"),
    path("signup/", SignupView.as_view(), name="signup"),
    path("<int:pk>/", MypageView.as_view(), name="mypage"),
    path("update-profile/", EditProfileView.as_view(), name="update_profile"),
    path("change-password/", ChangePasswordView.as_view(), name="change_password"),
]

books/models.py
from django.db import models
from core.models import CoreModel

# Create your models here.


class Book(CoreModel):

    """ Book Model """

    title = models.CharField(max_length=120)
    year = models.IntegerField()
    rating = models.IntegerField()
    cover_image = models.ImageField(
        null=True, blank=True, upload_to="book_cover")
    category = models.ForeignKey(
        "categories.Category", on_delete=models.CASCADE, related_name="books")
    writer = models.ForeignKey(
        "people.Person", on_delete=models.CASCADE, related_name="books")
    storyline = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.title

    def cut_storyline(self):
        if len(self.storyline) >= 300:
            preview = self.storyline[:300]
            read_more = self.storyline[300:]
            return {"preview": preview, "read_more": read_more}

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):

    PREF_BOOKS = "books"
    PREF_MOVIES = "movies"
    PREF_CHOICES = (
        (PREF_BOOKS, "Books"),
        (PREF_MOVIES, "Movies"),
    )

    LANG_EN = "english"
    LANG_KO = "korean"
    LANG_JP = "japaness"
    LANG_CHOICES = (
        (LANG_EN, "English"),
        (LANG_KO, "Korean"),
        (LANG_JP, "Japaness"),
    )

    bio = models.TextField()
    avatar = models.ImageField(
        null=True, blank=True, upload_to="user_avatar")
    preference = models.CharField(
        max_length=10, choices=PREF_CHOICES, default=PREF_MOVIES)
    language = models.CharField(
        max_length=20, choices=LANG_CHOICES, default=LANG_EN)
    fav_book_genre = models.ForeignKey(
        "categories.Category", on_delete=models.SET_NULL, null=True, related_name="book_users")
    fav_movie_genre = models.ForeignKey(
        "categories.Category", on_delete=models.SET_NULL, null=True, related_name="movie_users")

    def __str__(self):
        return self.username

books/forms.py
from dataclasses import field
from django import forms
from . import models


class CreateBookForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True

    class Meta:
        model = models.Book
        fields = [
            "title",
            "year",
            "rating",
            "cover_image",
            "category",
            "writer",
            "storyline",
        ]
        widgets = {
            "title": forms.TextInput(attrs={"class": "p-2"}),
            "year": forms.NumberInput(attrs={"class": "p-2"}),
            "rating": forms.NumberInput(attrs={"class": "p-2"}),
            "storyline": forms.Textarea(attrs={"class": "p-2"}),
        }
        required = (
            "title",
            "year",
            "rating",
            "category",
            "writer",
        )

    def clean(self):
        title = self.cleaned_data.get("title")

        if len(title) <= 0:
            self.add_error("title", forms.ValidationError(
                "title is not empty."))
        else:
            return self.cleaned_data

    # def save(self, *args, **kwargs):
    #     book = super().save(commit=False)
    #     return book

users/forms.py
from django import forms
from users.models import User


class LoginForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(
        attrs={"placeholder": "Email"}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={"placeholder": "Password"}))

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        #print(f"before: {self.cleaned_data}")
        try:
            user = User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError(
                    "Password is wrong."))
        except User.DoesNotExist:
            self.add_error("email", forms.ValidationError(
                "User does not exist."))
        #print(f"after: {self.cleaned_data}")


class SignUpForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("first_name", "last_name", "email")

    password = forms.CharField(widget=forms.PasswordInput)
    password1 = forms.CharField(
        widget=forms.PasswordInput, label="Password Confirm")

    def clean_first_name(self):
        first_name = self.cleaned_data.get("first_name")
        if len(first_name) <= 0:
            raise forms.ValidationError("Please input your first name.")
        else:
            return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data.get("last_name")
        if len(last_name) <= 0:
            raise forms.ValidationError("Please input your last name.")
        else:
            return last_name

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            user = User.objects.get(email=email)
            raise forms.ValidationError("This email already added.")
        except User.DoesNotExist:
            if len(email) <= 0:
                raise forms.ValidationError("Please input your email.")
            else:
                return email

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")
        if password != password1:
            raise forms.ValidationError(
                "Password confirmation does not match.")
        else:
            return password

    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user.username = email
        user.set_password(password)
        user.save()

books/views.py
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, FormView, DeleteView, UpdateView
from books.models import Book
from . import forms


# Create your views here.
class BooksView(ListView):
    """Show the Book lists"""

    model = Book
    paginate_by = 10
    paginate_orphans = 5
    ordering = "-created_at"
    context_object_name = "books"


class BookDetail(DetailView):
    """Show the book detail"""

    model = Book
    context_object_name = "book"


class BookCreate(FormView):
    """ Create new books"""
    form_class = forms.CreateBookForm
    template_name = "books/book_create.html"

    def get(self, request):
        form = self.get_form()
        return render(request, "books/book_create.html", {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():

            book = form.save()
            book.save()
            return redirect(reverse("books:book", kwargs={"pk": book.pk}))
        else:

            return render(request, "books/book_create.html", {"form": form})


class BookUpdate(UpdateView):
    model = Book
    template_name = "books/book_update.html"
    success_url = reverse_lazy("books:books")
    fields = ("title",
              "year",
              "rating",
              "cover_image",
              "category",
              "writer",
              "storyline",)


class BookDelete(DeleteView):
    """ Delete book information """
    model = Book
    success_url = reverse_lazy("books:books")

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

users/views.py
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.views import View
from django.views.generic import FormView, DetailView, UpdateView
from django.contrib.auth.views import PasswordChangeView
from users.forms import LoginForm, SignUpForm
from users.models import User

# Create your views here.


def logout_view(request):
    """Logout"""
    logout(request)
    return redirect(reverse("core:home"))


class LoginView(View):
    """Login"""

    def get(self, request):
        form = LoginForm()
        return render(request, "users/login.html", {"form": form})

    def post(self, request):
        form = LoginForm(request.POST)
        # print(form.errors)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=email, password=password)
            print("start")
            print(f"{email}, {password}")
            print(user)
            if user is not None:
                login(request, user)
                print("user")
                return redirect(reverse("core:home"))

        return render(request, "users/login.html", {"form": form})


class SignupView(FormView):
    """Sign up"""
    template_name = "users/signup.html"
    form_class = SignUpForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)


class MypageView(DetailView):
    """Show user's my page."""
    model = User
    template_name = "users/my_page.html"
    context_object_name = "user_obj"


class EditProfileView(UpdateView):
    """Edit user's profile"""
    model = User
    template_name = "users/update_profile.html"
    context_object_name = "user_obj"
    fields = (
        "first_name",
        "last_name",
        "bio",
        "avatar",
        "preference",
        "language",
        "fav_book_genre",
        "fav_movie_genre",
    )

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse_lazy("users:mypage", kwargs={"pk": self.object.pk})


class ChangePasswordView(PasswordChangeView):
    """Change user's password"""
    template_name = "users/change_password.html"
    success_url = reverse_lazy("core:home")

templates/mixins/books.html
<div>
    <a href="{% url "books:book" book.pk %}">
        <div class="flex flex-col justify-center items-center">
            <div class="w-64 h-96 relative group">
                {% if book.cover_image %}
                    <img class="w-64 rounded-lg filter group-hover:brightness-50" src="{{book.cover_image.url}}" />
                    <p class="text-white font-bold text-lg text-center absolute top-1/2 left-1/2 transform -translate-y-1/2 -translate-x-1/2 invisible group-hover:visible">{{book.title}}</p>         
                {% else %}
                    <div class="w-64 h-96 rounded-lg bg-gray-300 flex flex-col justify-center items-center filter hover:brightness-50">
                        <p class="text-white text-4xl"><i class="far fa-image"></i></p>
                        <p class="text-white text-3xl">No image</p>
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="my-3 pl-2">
            <p>
                <span class="text-gray-500"><i class="fas fa-star text-maincolor mr-1"></i>{{book.rating}}</span>
                <span class="text-sm text-blue-400 ml-1">{{book.year}}</span>
            </p>
            <p class="font-bold text-lg mt-1">{{book.title}}</p>       
        </div>
    </a>

    <div class="group">
        <a class="flex justify-center items-center py-2 my-5 border border-pink-500 rounded-lg group-hover:bg-pink-500" href="#">
            <p class="text-pink-500 group-hover:text-white"><i class="fas fa-plus"></i><span class="ml-2">Favorite lists</span></p>
        </a>
    </div>
</div>

templates/mixins/data_form.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            <span>{{error}}</span>
        {% endfor %}
    {% endif %}

    <div class="border border-gray-200 p-8">
        {% for field in form %}
            <dl class="flex mb-5">
                <dt class="w-28 text-gray-500 font-bold" for="{{field.auto_id}}">
                    {{field.label}}
                    {% if field.field.required %}
                        <span class="text-red-500">*</span>
                    {% endif %}
                </dt>
                <dd class="text-gray-700
                {% if field.field.widget.input_type == 'text' %}w-1/2 border shadow-sm
                {% elif field.field.widget.input_type == 'number' %}w-1/4 border shadow-sm
                {% elif field.field.widget.input_type == 'select' %}w-1/4
                {% elif field.field.widget.input_type == None %}w-full border shadow-sm
                {% endif %}">
                    {{field}}
                </dd>
            </dl>
            {% if field.errors %}
                {% for error in field.errors %}
                    <span class="text-red-700 font-medium text-sm">{{error}}</span>
                {% endfor %}
            {% endif %}
        {% endfor %}
    </div>

    <button class="my-6 mr-2 bg-maincolor p-3 rounded-lg text-white hover:bg-blue-400">{{cta}}</button>
    <a href="{% url 'books:books' %}" class="my-6 bg-gray-200 px-3 py-4 rounded-lg text-gray-800 hover:shadow-md">Close</a>
</form>

templates/mixins/delete_popup.html
<div id="delete_popup" class="popup">
    <div class="fixed top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 z-10 w-3/4 h-1/4 max-w-1/3 max-h-1/4 border border-maincolor bg-white shadow-lg">
        <div class="flex flex-col justify-around items-center w-full h-full py-10">
            <p class="font-bold text-lg">Are you sure you want to delete?</p>
            <div class="w-full flex justify-end pr-5">
                <button onclick="ClosePopup()" class="bg-gray-100 mr-3 py-1 px-5 rounded-lg italic text-gray-600 hover:shadow-lg">
                    No
                </button>

                <form method="post" action="{% url 'books:delete' book.pk %}">
                    {% csrf_token %}
                    <a href="{% url "books:delete" book.pk %}">
                        <button class="bg-red-500 border border-red-500 py-1 px-4 rounded-lg text-white font-bold hover:bg-white hover:text-red-500">
                            Yes, I delete
                        </button>
                    </a>
                </form>
            </div>
        </div>
    </div>
</div>

templates/mixins/login_form.html
<form method="POST" enctype="multipart/form-data">
    {%csrf_token%}

    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            <span class="text-red-500">{{error}}</span> 
        {% endfor %}
    {% endif %}

    <div class="border border-gray-300 p-8 rounded-md shadow-sm">
    {% for field in form %}
        <div class="p-4 border">
            {{field}}
        </div>
        {% if field.errors %}
            {% for error in field.errors %}
                <p class="text-red-500 font-medium text-sm pl-3">{{error}}</p>
            {% endfor %}
        {% endif %}
    {% endfor %}
    
    <button class="w-full py-4 mt-8 rounded-md bg-maincolor text-xl font-bold text-white">{{cta}}</button>
</div>
</form>

templates/mixins/movies.html
<a href="{% url "movies:movie" movie.pk %}">
    <h1>{{movie.title}}</h1>
    <h3>{{movie.year}}</h3>
</a>

templates/mixins/signup_user_form.html
<form method="POST" enctype="multipart/form-data">
    {%csrf_token%}

    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            <span class="text-red-500">{{error}}</span> 
        {% endfor %}
    {% endif %}

    <div class="border border-gray-300 p-8 rounded-md shadow-sm">
    {% for field in form %}
        <div class="mb-6">
            <label class="text-gray-500">{{field.label}}</label>
            <div class="p-4 border shadow-sm">
                {{field}}
            </div>
            {% if field.errors %}
                {% for error in field.errors %}
                    <p class="text-red-500 font-medium text-sm pl-3">{{error}}</p>
                {% endfor %}
            {% endif %}
        </div>
    {% endfor %}
    
    <button class="w-full py-4 mt-8 rounded-md bg-maincolor text-xl font-bold text-white">{{cta}}</button>
</div>
</form>

templates/mixins/user_avatar.html
{% if user.avatar %}
    <div class="h-28 w-28 rounded-full bg-cover" style="background-image: url({{user.avatar.url}});">
{% else %}
    <div class="h-28 w-28 bg-gray-700 rounded-full text-white flex justify-center items-center overflow-hidden">
        <span class="text-3xl">{{user.first_name|first}}{{user.last_name|first}}</span>
    {% endif %}
</div> 

templates/mixins/user_form.html
<form method="POST" enctype="multipart/form-data">
    {%csrf_token%}

    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            <span class="text-red-500">{{error}}</span> 
        {% endfor %}
    {% endif %}

    <div class="border border-gray-300 p-8 rounded-md shadow-sm">
    {% for field in form %}
        <div class="p-4 border">
            {{field}}
        </div>
        {% if field.errors %}
            {% for error in field.errors %}
                <p class="text-red-500 font-medium text-sm pl-3">{{error}}</p>
            {% endfor %}
        {% endif %}
    {% endfor %}
    
    <button class="w-full py-4 mt-8 rounded-md bg-maincolor text-xl font-bold text-white">{{cta}}</button>
</div>
</form>