books/urls.py
from django.urls import path
from books.views import BooksView, BookDetail, BookCreate, BookDelete, BookUpdate

app_name = "books"

urlpatterns = [
    path("", BooksView.as_view(), name="books"),
    path("<int:pk>/", BookDetail.as_view(), name="book"),
    path("create/", BookCreate.as_view(), name="create"),
    path("update/<int:pk>/", BookUpdate.as_view(), name="update"),
    path("delete/<int:pk>/", BookDelete.as_view(), name="delete"),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("books/", include("books.urls",  namespace="books")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import home


app_name = "core"

urlpatterns = [
    path("", home, name="home"),
]

books/models.py
from django.db import models
from core.models import CoreModel

# Create your models here.


class Book(CoreModel):

    """ Book Model """

    title = models.CharField(max_length=120)
    year = models.IntegerField()
    rating = models.IntegerField()
    cover_image = models.ImageField(
        null=True, blank=True, upload_to="book_cover")
    category = models.ForeignKey(
        "categories.Category", on_delete=models.CASCADE, related_name="books")
    writer = models.ForeignKey(
        "people.Person", on_delete=models.CASCADE, related_name="books")
    storyline = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.title

    def cut_storyline(self):
        if len(self.storyline) >= 300:
            preview = self.storyline[:300]
            read_more = self.storyline[300:]
            return {"preview": preview, "read_more": read_more}

books/forms.py
from dataclasses import field
from django import forms
from . import models


class CreateBookForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True

    class Meta:
        model = models.Book
        fields = [
            "title",
            "year",
            "rating",
            "cover_image",
            "category",
            "writer",
            "storyline",
        ]
        widgets = {
            "title": forms.TextInput(attrs={"class": "p-2"}),
            "year": forms.NumberInput(attrs={"class": "p-2"}),
            "rating": forms.NumberInput(attrs={"class": "p-2"}),
            "storyline": forms.Textarea(attrs={"class": "p-2"}),
        }
        required = (
            "title",
            "year",
            "rating",
            "category",
            "writer",
        )

    def clean(self):
        title = self.cleaned_data.get("title")

        if len(title) <= 0:
            self.add_error("title", forms.ValidationError(
                "title is not empty."))
        else:
            return self.cleaned_data

    # def save(self, *args, **kwargs):
    #     book = super().save(commit=False)
    #     return book

books/views.py
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, FormView, DeleteView, UpdateView
from books.models import Book
from . import forms


# Create your views here.
class BooksView(ListView):
    """Show the Book lists"""

    model = Book
    paginate_by = 10
    paginate_orphans = 5
    ordering = "-created_at"
    context_object_name = "books"


class BookDetail(DetailView):
    """Show the book detail"""

    model = Book
    context_object_name = "book"


class BookCreate(FormView):
    """ Create new books"""
    form_class = forms.CreateBookForm
    template_name = "books/book_create.html"

    def get(self, request):
        form = self.get_form()
        return render(request, "books/book_create.html", {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():

            book = form.save()
            book.save()
            return redirect(reverse("books:book", kwargs={"pk": book.pk}))
        else:

            return render(request, "books/book_create.html", {"form": form})


class BookUpdate(UpdateView):
    model = Book
    template_name = "books/book_update.html"
    success_url = reverse_lazy("books:books")
    fields = ("title",
              "year",
              "rating",
              "cover_image",
              "category",
              "writer",
              "storyline",)


class BookDelete(DeleteView):
    """ Delete book information """
    model = Book
    success_url = reverse_lazy("books:books")

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

templates/books/book_create.html
{% extends 'base.html' %}

{% block page_title %}
    Create Book
{% endblock page_title %}

{% block content %}
    <h1 class="my-8 text-3xl font-bold text-maincolor">Create Book infomation</h1>
    {% include 'mixins/data_form.html' with form=form cta="Save" %}
{% endblock content %}

templates/books/book_detail.html
{% extends "base.html"%}
{% load static %}

{% block page_title %}
    {{book.title}}
{% endblock page_title %}

{% block content %}
    <div id="detail">
        <!-- back to the lists button -->
        <a href="{% url "books:books" %}">
            <div class="my-8 pl-4 text-sm text-blue-500 hover:text-blue-700">
                <i class="fas fa-angle-left"></i> back
            </div>
        </a>

        <div class="flex my-8">
            <!-- draw cover image -->
            <div class="min-w-fit h-full mr-16 shadow-xl hover:shadow-2xl">
                {% if book.cover_image %}
                    <img class="w-96 rounded-lg" src="{{book.cover_image.url}}" />
                {%else%}
                    <div class="w-96 h-96 rounded-lg bg-gray-300 flex justify-center items-center">
                        <p class="text-white text-3xl">No image</p>
                    </div>
                {% endif %}
                
            </div>

            <!-- show infomation (title, storyline, year, rating...)-->
            <div class="w-1/2 flex flex-col pt-6">
                <h1 class="text-4xl mb-5">{{book.title}}</h1>
                <p class="text-gray-500 mb-2"><span class="mr-3">{{book.writer}}</span>  |  <span class="ml-3">{{book.year}}</span></p>
                <p>
                    <span class="font-bold text-lg"><i class="fas fa-star text-maincolor text-xl mr-1"></i>{{book.rating}}</span>
                    <span class="bg-maincolor text-white ml-3 px-2 py-1 rounded-xl">{{book.category}}</span>
                </p>

                <div class="mt-10 text-justify text-gray-600 border-b border-gray-300 pb-4">
                    {% if book.cut_storyline.preview %}
                        <p class="storyline">{{book.cut_storyline.preview | linebreaksbr}}
                            <span class="dots">...</span>
                            <span class="more-text">{{book.cut_storyline.read_more | linebreaksbr}}</span>
                        </p>
                        <button class="read-more-btn">Read more</button>
                    {%else%}
                        <p>{{book.storyline}}</p>                    
                    {% endif %}
                </div>

                <!-- Favorite lists button-->
                <div class="group">
                    <a class="flex justify-center items-center py-2 my-5 border border-pink-500 rounded-lg group-hover:bg-pink-500" href="#">
                        <p class="text-pink-500 group-hover:text-white"><i class="fas fa-plus"></i><span class="ml-2">Favorite lists</span></p>
                    </a>
                </div>
            </div>
        </div>

        <div class="flex">
            <!-- Update Button -->
            <div class="group mr-3 mb-5">
                <a class="flex justify-center items-center px-2 py-2 border border-green-500 rounded-lg group-hover:bg-green-500" href="{% url 'books:update' book.pk%}">
                    <p class="text-green-500 group-hover:text-white">Update</p>
                </a>
            </div>
            <!-- Delete Button -->
            <div class="group">
                <button id="delete_btn" class="flex justify-center items-center py-2 px-2 border border-red-500 rounded-lg group-hover:bg-red-500">
                    <p class="text-red-500 group-hover:text-white">Delete</p>
                </button>
            </div>
        </div>

        <div>
            <h1 class="text-3xl font-bold text-maincolor">Reviews</h1>
        </div>
    </div>
    {% include "mixins/delete_popup.html" %}
{% endblock content %}

templates/books/book_form.html
{% extends 'base.html' %}

{% block page_title %}
    Create Book
{% endblock page_title %}

{% block content %}
    <h1 class="my-8 text-3xl font-bold text-maincolor">Create Book infomation</h1>
    {% include 'mixins/form.html' with form=form cta="Save" %}
{% endblock content %}

templates/books/book_list.html
{% extends "base.html" %}

{% block page_title %}
Books
{% endblock page_title %}

{% block content %}
    <div class="mt-6">
        <div class="flex justify-between items-center mb-8">
            <h1 class="text-3xl font-bold text-maincolor">Books</h1>
            <h3 class="text-sm text-pink-400 hover:text-red-500"><a href="{% url 'books:create' %}">Create ></a></h3>
        </div>
        <div class="grid grid-cols-colsAutoFill gap-4">
            {% for book in  books %}
                {% include "mixins/books.html" with book=book%}
            {% endfor %}
        </div>
    </div>

    {% include "partials/paginator.html" %}
{% endblock content %}

templates/books/book_update.html
{% extends 'base.html' %}

{% block page_title %}
    Update Book
{% endblock page_title %}

{% block content %}
    <h1 class="my-8 text-3xl font-bold text-maincolor">Update {{book.title}} infomation</h1>
    {% include 'mixins/data_form.html' with form=form cta="Update" %}
{% endblock content %}