config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("books/", include("books.urls",  namespace="books")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import home


app_name = "core"

urlpatterns = [
    path("", home, name="home"),
]

movies/urls.py
from django.urls import path
from movies.views import MoviesView, MovieDetail, UpdateMovie, CreateMovie, DeleteMovie

app_name = "movies"

urlpatterns = [
    path("", MoviesView.as_view(), name="movies"),
    path("<int:pk>/", MovieDetail.as_view(), name="movie"),
    path("<int:pk>/update/", UpdateMovie.as_view(), name="update"),
    path("create/", CreateMovie.as_view(), name="create"),
    path("<int:pk>/delete/", DeleteMovie.as_view(), name="delete"),
]

movies/models.py
from django.db import models
from core.models import CoreModel

# Create your models here.


class Movie(CoreModel):
    """ Movie Model """

    title = models.CharField(max_length=120)
    year = models.IntegerField()
    cover_image = models.ImageField(null=True, blank=True)
    rating = models.IntegerField()
    category = models.ForeignKey(
        "categories.Category", on_delete=models.CASCADE, related_name="movies")
    director = models.ForeignKey(
        "people.Person", on_delete=models.CASCADE, related_name="movies")
    cast = models.ManyToManyField("people.Person", null=True, blank=True)

    def __str__(self):
        return self.title

movies/views.py
from django.core.paginator import Paginator
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.shortcuts import render
from movies.models import Movie

# Create your views here.


class MoviesView(ListView):
    """Show the Movie lists"""

    model = Movie
    paginate_by = 10
    paginate_orphans = 5
    ordering = "-created_at"
    context_object_name = "movies"


class MovieDetail(DetailView):
    """ Show the movie details"""
    model = Movie
    context_object_name = "movie"


class UpdateMovie(UpdateView):
    """ Edit Movie's information """
    model = Movie
    fields = (
        "title",
        "year",
        "cover_image",
        "rating",
        "category",
        "director",
        "cast",
    )

    def get_success_url(self):
        movie_pk = self.kwargs.get("pk")
        print(movie_pk)
        return reverse("movies:movie", kwargs={"pk": movie_pk})


class CreateMovie(CreateView):
    """ Create Movie's information """
    model = Movie
    fields = (
        "title",
        "year",
        "cover_image",
        "rating",
        "category",
        "director",
        "cast",
    )

    def get_success_url(self):
        return reverse("movies:movies")


class DeleteMovie(DeleteView):
    """Delete Movie's information"""
    model = Movie
    success_url = reverse_lazy("movies:movies")

templates/movies/movie_confirm_delete.html
{% extends "base.html" %}
{%block page_title%}
    Delete Movie
{%endblock page_title%}

{% block content %}
    <h1>{{movie.title}}</h1>
    <p>Do you want to delete this movie?</p>
   <form method="POST">
       {%csrf_token%}
       <input type="submit" value="Delete">
   </form>
{%endblock content %}

templates/movies/movie_detail.html
{% extends "base.html"%}

{% block page_title %}
    {{movie.title}}
{% endblock page_title %}

{% block content %}
    <div>
        <h1>{{movie.title}}</h1>
        <p>year : {{movie.year}}</p>
        <p>rating : {{movie.rating}}</p>
        <p>category : {{movie.category}}</p>
        <p>director : {{movie.director}}</p>
        <p>cast</p>
        {% for cast in movie.cast.all %}
            <p>{{cast}}</p>
        {% endfor %}
    </div>

    <div>
        <a href="{% url "movies:update" movie.pk %}">Update Movie</a>
        <a href="{% url "movies:delete" movie.pk %}">Delete Movie</a>
    </div>
{% endblock content %}

templates/movies/movie_form.html
{% extends "base.html" %}

{% block page_title %}
    Movie
{% endblock page_title%}

{% block content %}
    {% include "mixins/form.html" with form=form cta="Save" %}
{% endblock content %}

templates/movies/movie_list.html
{% extends "base.html" %}

{% block page_title %}
Movies
{% endblock page_title %}

{% block content %}
    <div class="mt-6">
        <div class="flex justify-between items-center mb-8">
            <h1 class="text-3xl font-bold text-maincolor">Movies</h1>
            <h3 class="text-sm text-pink-400 hover:text-red-500"><a href="{% url "movies:create" %}">Create ></a></h3>
        </div>
        {% for movie in  movies %}
            {% include "mixins/movies.html" with movie=movie%}
        {% endfor %}
    </div>

    {% include "partials/paginator.html" %}
{% endblock content %}